spring.application.name=event-platform
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# in-memory database, data will be lost when the application stops
spring.datasource.url=jdbc:h2:mem:testdb 

# if you want to persist data, uncomment the line below and comment out the previous one
#spring.datasource.url=jdbc:h2:file:./data/testdb

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

app.base-url=${APP_BASE_URL:http://localhost:8080}
app.support-email=${SUPPORT_EMAIL:support@example.com}
stripe.secret-key=${STRIPE_SECRET_KEY:}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:}
stripe.public-key=${STRIPE_PUBLIC_KEY:}
